version: "3"

services:
    ldap:
        build: ./LDAP_server
        container_name: LDAP-10.9.0.5
        tty: true
        ports:
            - "1389:1389"
            - "8888:8888"
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

    server:
        build: ./vulnerable_server
        image: ghcr.io/christophetd/log4shell-vulnerable-app
        container_name: vulnerable-app
        tty: true
        ports:
            - "8080:8080"
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
